/*
Idaho Counties loader (88 clues from IdahoCounties.csv).

1. Insert entries for county names and county seats.
2. Insert 88 clues (44 county -> seat, 44 license-plate code -> county).
3. Link clues to clue_collection id "idaho_counties".

Prerequisite: clue_collection row with id = 'idaho_counties' must already exist.
*/

--INSERT INTO clue_collection (id, "name", "description", lang, author, source) VALUES
--('idaho_counties', 'Idaho Counties', 'Clues for Idaho counties', 'en', 'Cruzi', 'Cruzi');

-- Entries for all answer strings (county names and county seats)
INSERT INTO "entry" ("entry", base_form, lang, "length", display_text, entry_type) VALUES
-- County names
('ADA', null, 'en', 3, 'Ada', 'Proper Name'),
('ADAMS', null, 'en', 5, 'Adams', 'Proper Name'),
('BANNOCK', null, 'en', 7, 'Bannock', 'Proper Name'),
('BEARLAKE', null, 'en', 8, 'Bear Lake', 'Proper Name'),
('BENEWAH', null, 'en', 7, 'Benewah', 'Proper Name'),
('BINGHAM', null, 'en', 7, 'Bingham', 'Proper Name'),
('BLAINE', null, 'en', 6, 'Blaine', 'Proper Name'),
('BOISE', null, 'en', 5, 'Boise', 'Proper Name'),
('BONNER', null, 'en', 6, 'Bonner', 'Proper Name'),
('BONNEVILLE', null, 'en', 10, 'Bonneville', 'Proper Name'),
('BOUNDARY', null, 'en', 8, 'Boundary', 'Proper Name'),
('BUTTE', null, 'en', 5, 'Butte', 'Proper Name'),
('CAMAS', null, 'en', 5, 'Camas', 'Proper Name'),
('CANYON', null, 'en', 6, 'Canyon', 'Proper Name'),
('CARIBOU', null, 'en', 7, 'Caribou', 'Proper Name'),
('CASSIA', null, 'en', 6, 'Cassia', 'Proper Name'),
('CLARK', null, 'en', 5, 'Clark', 'Proper Name'),
('CLEARWATER', null, 'en', 10, 'Clearwater', 'Proper Name'),
('CUSTER', null, 'en', 6, 'Custer', 'Proper Name'),
('ELMORE', null, 'en', 6, 'Elmore', 'Proper Name'),
('FRANKLIN', null, 'en', 8, 'Franklin', 'Proper Name'),
('FREMONT', null, 'en', 7, 'Fremont', 'Proper Name'),
('GEM', null, 'en', 3, 'Gem', 'Proper Name'),
('GOODING', null, 'en', 7, 'Gooding', 'Proper Name'),
('IDAHO', null, 'en', 5, 'Idaho', 'Proper Name'),
('JEFFERSON', null, 'en', 9, 'Jefferson', 'Proper Name'),
('JEROME', null, 'en', 6, 'Jerome', 'Proper Name'),
('KOOTENAI', null, 'en', 8, 'Kootenai', 'Proper Name'),
('LATAH', null, 'en', 5, 'Latah', 'Proper Name'),
('LEMHI', null, 'en', 5, 'Lemhi', 'Proper Name'),
('LEWIS', null, 'en', 5, 'Lewis', 'Proper Name'),
('LINCOLN', null, 'en', 7, 'Lincoln', 'Proper Name'),
('MADISON', null, 'en', 7, 'Madison', 'Proper Name'),
('MINIDOKA', null, 'en', 8, 'Minidoka', 'Proper Name'),
('NEZPERCE', null, 'en', 8, 'Nez Perce', 'Proper Name'),
('ONEIDA', null, 'en', 6, 'Oneida', 'Proper Name'),
('OWYHEE', null, 'en', 6, 'Owyhee', 'Proper Name'),
('PAYETTE', null, 'en', 7, 'Payette', 'Proper Name'),
('POWER', null, 'en', 5, 'Power', 'Proper Name'),
('SHOSHONE', null, 'en', 8, 'Shoshone', 'Proper Name'),
('TETON', null, 'en', 5, 'Teton', 'Proper Name'),
('TWINFALLS', null, 'en', 9, 'Twin Falls', 'Proper Name'),
('VALLEY', null, 'en', 6, 'Valley', 'Proper Name'),
('WASHINGTON', null, 'en', 10, 'Washington', 'Proper Name'),
-- County seats
('COUNCIL', null, 'en', 7, 'Council', 'Proper Name'),
('POCATELLO', null, 'en', 9, 'Pocatello', 'Proper Name'),
('PARIS', null, 'en', 5, 'Paris', 'Proper Name'),
('STMARIES', null, 'en', 8, 'St. Maries', 'Proper Name'),
('BLACKFOOT', null, 'en', 9, 'Blackfoot', 'Proper Name'),
('HAILEY', null, 'en', 6, 'Hailey', 'Proper Name'),
('IDAHOCITY', null, 'en', 9, 'Idaho City', 'Proper Name'),
('SANDPOINT', null, 'en', 9, 'Sandpoint', 'Proper Name'),
('IDAHOFALLS', null, 'en', 10, 'Idaho Falls', 'Proper Name'),
('BONNERSFERRY', null, 'en', 12, 'Bonners Ferry', 'Proper Name'),
('ARCO', null, 'en', 4, 'Arco', 'Proper Name'),
('FAIRFIELD', null, 'en', 9, 'Fairfield', 'Proper Name'),
('CALDWELL', null, 'en', 8, 'Caldwell', 'Proper Name'),
('SODASPRINGS', null, 'en', 11, 'Soda Springs', 'Proper Name'),
('BURLEY', null, 'en', 6, 'Burley', 'Proper Name'),
('DUBOIS', null, 'en', 6, 'Dubois', 'Proper Name'),
('OROFINO', null, 'en', 7, 'Orofino', 'Proper Name'),
('CHALLIS', null, 'en', 7, 'Challis', 'Proper Name'),
('MOUNTAINHOME', null, 'en', 12, 'Mountain Home', 'Proper Name'),
('PRESTON', null, 'en', 7, 'Preston', 'Proper Name'),
('SAINTANTHONY', null, 'en', 12, 'Saint Anthony', 'Proper Name'),
('EMMETT', null, 'en', 6, 'Emmett', 'Proper Name'),
('GRANGEVILLE', null, 'en', 11, 'Grangeville', 'Proper Name'),
('RIGBY', null, 'en', 5, 'Rigby', 'Proper Name'),
('COEURDALENE', null, 'en', 12, 'Coeur d''Alene', 'Proper Name'),
('MOSCOW', null, 'en', 6, 'Moscow', 'Proper Name'),
('SALMON', null, 'en', 6, 'Salmon', 'Proper Name'),
('REXBURG', null, 'en', 7, 'Rexburg', 'Proper Name'),
('RUPERT', null, 'en', 6, 'Rupert', 'Proper Name'),
('LEWISTON', null, 'en', 8, 'Lewiston', 'Proper Name'),
('MALADCITY', null, 'en', 9, 'Malad City', 'Proper Name'),
('MURPHY', null, 'en', 6, 'Murphy', 'Proper Name'),
('AMERICANFALLS', null, 'en', 13, 'American Falls', 'Proper Name'),
('WALLACE', null, 'en', 7, 'Wallace', 'Proper Name'),
('DRIGGS', null, 'en', 6, 'Driggs', 'Proper Name'),
('CASCADE', null, 'en', 7, 'Cascade', 'Proper Name'),
('WEISER', null, 'en', 6, 'Weiser', 'Proper Name')
ON CONFLICT ("entry", lang) DO NOTHING;

-- County name -> county seat clues
INSERT INTO clue (id, "entry", lang, sense_id, custom_clue, custom_display_text) VALUES
('idaho_county_clue_001', 'BOISE', 'en', NULL, 'Ada', 'Boise'),
('idaho_county_clue_002', 'COUNCIL', 'en', NULL, 'Adams', 'Council'),
('idaho_county_clue_003', 'POCATELLO', 'en', NULL, 'Bannock', 'Pocatello'),
('idaho_county_clue_004', 'PARIS', 'en', NULL, 'Bear Lake', 'Paris'),
('idaho_county_clue_005', 'STMARIES', 'en', NULL, 'Benewah', 'St. Maries'),
('idaho_county_clue_006', 'BLACKFOOT', 'en', NULL, 'Bingham', 'Blackfoot'),
('idaho_county_clue_007', 'HAILEY', 'en', NULL, 'Blaine', 'Hailey'),
('idaho_county_clue_008', 'IDAHOCITY', 'en', NULL, 'Boise', 'Idaho City'),
('idaho_county_clue_009', 'SANDPOINT', 'en', NULL, 'Bonner', 'Sandpoint'),
('idaho_county_clue_010', 'IDAHOFALLS', 'en', NULL, 'Bonneville', 'Idaho Falls'),
('idaho_county_clue_011', 'BONNERSFERRY', 'en', NULL, 'Boundary', 'Bonners Ferry'),
('idaho_county_clue_012', 'ARCO', 'en', NULL, 'Butte', 'Arco'),
('idaho_county_clue_013', 'FAIRFIELD', 'en', NULL, 'Camas', 'Fairfield'),
('idaho_county_clue_014', 'CALDWELL', 'en', NULL, 'Canyon', 'Caldwell'),
('idaho_county_clue_015', 'SODASPRINGS', 'en', NULL, 'Caribou', 'Soda Springs'),
('idaho_county_clue_016', 'BURLEY', 'en', NULL, 'Cassia', 'Burley'),
('idaho_county_clue_017', 'DUBOIS', 'en', NULL, 'Clark', 'Dubois'),
('idaho_county_clue_018', 'OROFINO', 'en', NULL, 'Clearwater', 'Orofino'),
('idaho_county_clue_019', 'CHALLIS', 'en', NULL, 'Custer', 'Challis'),
('idaho_county_clue_020', 'MOUNTAINHOME', 'en', NULL, 'Elmore', 'Mountain Home'),
('idaho_county_clue_021', 'PRESTON', 'en', NULL, 'Franklin', 'Preston'),
('idaho_county_clue_022', 'SAINTANTHONY', 'en', NULL, 'Fremont', 'Saint Anthony'),
('idaho_county_clue_023', 'EMMETT', 'en', NULL, 'Gem', 'Emmett'),
('idaho_county_clue_024', 'GOODING', 'en', NULL, 'Gooding', 'Gooding'),
('idaho_county_clue_025', 'GRANGEVILLE', 'en', NULL, 'Idaho', 'Grangeville'),
('idaho_county_clue_026', 'RIGBY', 'en', NULL, 'Jefferson', 'Rigby'),
('idaho_county_clue_027', 'JEROME', 'en', NULL, 'Jerome', 'Jerome'),
('idaho_county_clue_028', 'COEURDALENE', 'en', NULL, 'Kootenai', 'Coeur d''Alene'),
('idaho_county_clue_029', 'MOSCOW', 'en', NULL, 'Latah', 'Moscow'),
('idaho_county_clue_030', 'SALMON', 'en', NULL, 'Lemhi', 'Salmon'),
('idaho_county_clue_031', 'NEZPERCE', 'en', NULL, 'Lewis', 'Nezperce'),
('idaho_county_clue_032', 'SHOSHONE', 'en', NULL, 'Lincoln', 'Shoshone'),
('idaho_county_clue_033', 'REXBURG', 'en', NULL, 'Madison', 'Rexburg'),
('idaho_county_clue_034', 'RUPERT', 'en', NULL, 'Minidoka', 'Rupert'),
('idaho_county_clue_035', 'LEWISTON', 'en', NULL, 'Nez Perce', 'Lewiston'),
('idaho_county_clue_036', 'MALADCITY', 'en', NULL, 'Oneida', 'Malad City'),
('idaho_county_clue_037', 'MURPHY', 'en', NULL, 'Owyhee', 'Murphy'),
('idaho_county_clue_038', 'PAYETTE', 'en', NULL, 'Payette', 'Payette'),
('idaho_county_clue_039', 'AMERICANFALLS', 'en', NULL, 'Power', 'American Falls'),
('idaho_county_clue_040', 'WALLACE', 'en', NULL, 'Shoshone', 'Wallace'),
('idaho_county_clue_041', 'DRIGGS', 'en', NULL, 'Teton', 'Driggs'),
('idaho_county_clue_042', 'TWINFALLS', 'en', NULL, 'Twin Falls', 'Twin Falls'),
('idaho_county_clue_043', 'CASCADE', 'en', NULL, 'Valley', 'Cascade'),
('idaho_county_clue_044', 'WEISER', 'en', NULL, 'Washington', 'Weiser')
ON CONFLICT (id) DO UPDATE SET
  "entry" = EXCLUDED."entry",
  lang = EXCLUDED.lang,
  custom_clue = EXCLUDED.custom_clue,
  custom_display_text = EXCLUDED.custom_display_text;

-- License-plate county code -> county name clues
INSERT INTO clue (id, "entry", lang, sense_id, custom_clue, custom_display_text) VALUES
('idaho_code_clue_001', 'ADA', 'en', NULL, '1A', 'Ada'),
('idaho_code_clue_002', 'ADAMS', 'en', NULL, '2A', 'Adams'),
('idaho_code_clue_003', 'BANNOCK', 'en', NULL, '1B', 'Bannock'),
('idaho_code_clue_004', 'BEARLAKE', 'en', NULL, '2B', 'Bear Lake'),
('idaho_code_clue_005', 'BENEWAH', 'en', NULL, '3B', 'Benewah'),
('idaho_code_clue_006', 'BINGHAM', 'en', NULL, '4B', 'Bingham'),
('idaho_code_clue_007', 'BLAINE', 'en', NULL, '5B', 'Blaine'),
('idaho_code_clue_008', 'BOISE', 'en', NULL, '6B', 'Boise'),
('idaho_code_clue_009', 'BONNER', 'en', NULL, '7B', 'Bonner'),
('idaho_code_clue_010', 'BONNEVILLE', 'en', NULL, '8B', 'Bonneville'),
('idaho_code_clue_011', 'BOUNDARY', 'en', NULL, '9B', 'Boundary'),
('idaho_code_clue_012', 'BUTTE', 'en', NULL, '10B', 'Butte'),
('idaho_code_clue_013', 'CAMAS', 'en', NULL, '1C', 'Camas'),
('idaho_code_clue_014', 'CANYON', 'en', NULL, '2C', 'Canyon'),
('idaho_code_clue_015', 'CARIBOU', 'en', NULL, '3C', 'Caribou'),
('idaho_code_clue_016', 'CASSIA', 'en', NULL, '4C', 'Cassia'),
('idaho_code_clue_017', 'CLARK', 'en', NULL, '5C', 'Clark'),
('idaho_code_clue_018', 'CLEARWATER', 'en', NULL, '6C', 'Clearwater'),
('idaho_code_clue_019', 'CUSTER', 'en', NULL, '7C', 'Custer'),
('idaho_code_clue_020', 'ELMORE', 'en', NULL, 'E', 'Elmore'),
('idaho_code_clue_021', 'FRANKLIN', 'en', NULL, '1F', 'Franklin'),
('idaho_code_clue_022', 'FREMONT', 'en', NULL, '2F', 'Fremont'),
('idaho_code_clue_023', 'GEM', 'en', NULL, '1G', 'Gem'),
('idaho_code_clue_024', 'GOODING', 'en', NULL, '2G', 'Gooding'),
('idaho_code_clue_025', 'IDAHO', 'en', NULL, 'I', 'Idaho'),
('idaho_code_clue_026', 'JEFFERSON', 'en', NULL, '1J', 'Jefferson'),
('idaho_code_clue_027', 'JEROME', 'en', NULL, '2J', 'Jerome'),
('idaho_code_clue_028', 'KOOTENAI', 'en', NULL, 'K', 'Kootenai'),
('idaho_code_clue_029', 'LATAH', 'en', NULL, '1L', 'Latah'),
('idaho_code_clue_030', 'LEMHI', 'en', NULL, '2L', 'Lemhi'),
('idaho_code_clue_031', 'LEWIS', 'en', NULL, '3L', 'Lewis'),
('idaho_code_clue_032', 'LINCOLN', 'en', NULL, '4L', 'Lincoln'),
('idaho_code_clue_033', 'MADISON', 'en', NULL, '1M', 'Madison'),
('idaho_code_clue_034', 'MINIDOKA', 'en', NULL, '2M', 'Minidoka'),
('idaho_code_clue_035', 'NEZPERCE', 'en', NULL, 'N', 'Nez Perce'),
('idaho_code_clue_036', 'ONEIDA', 'en', NULL, '1O', 'Oneida'),
('idaho_code_clue_037', 'OWYHEE', 'en', NULL, '2O', 'Owyhee'),
('idaho_code_clue_038', 'PAYETTE', 'en', NULL, '1P', 'Payette'),
('idaho_code_clue_039', 'POWER', 'en', NULL, '2P', 'Power'),
('idaho_code_clue_040', 'SHOSHONE', 'en', NULL, 'S', 'Shoshone'),
('idaho_code_clue_041', 'TETON', 'en', NULL, '1T', 'Teton'),
('idaho_code_clue_042', 'TWINFALLS', 'en', NULL, '2T', 'Twin Falls'),
('idaho_code_clue_043', 'VALLEY', 'en', NULL, 'V', 'Valley'),
('idaho_code_clue_044', 'WASHINGTON', 'en', NULL, 'W', 'Washington')
ON CONFLICT (id) DO UPDATE SET
  "entry" = EXCLUDED."entry",
  lang = EXCLUDED.lang,
  custom_clue = EXCLUDED.custom_clue,
  custom_display_text = EXCLUDED.custom_display_text;

-- Link all clues to the idaho_counties collection
INSERT INTO collection__clue (collection_id, clue_id, "order", metadata1, metadata2) VALUES
('idaho_counties', 'idaho_county_clue_001', 1, NULL, NULL),
('idaho_counties', 'idaho_county_clue_002', 2, NULL, NULL),
('idaho_counties', 'idaho_county_clue_003', 3, NULL, NULL),
('idaho_counties', 'idaho_county_clue_004', 4, NULL, NULL),
('idaho_counties', 'idaho_county_clue_005', 5, NULL, NULL),
('idaho_counties', 'idaho_county_clue_006', 6, NULL, NULL),
('idaho_counties', 'idaho_county_clue_007', 7, NULL, NULL),
('idaho_counties', 'idaho_county_clue_008', 8, NULL, NULL),
('idaho_counties', 'idaho_county_clue_009', 9, NULL, NULL),
('idaho_counties', 'idaho_county_clue_010', 10, NULL, NULL),
('idaho_counties', 'idaho_county_clue_011', 11, NULL, NULL),
('idaho_counties', 'idaho_county_clue_012', 12, NULL, NULL),
('idaho_counties', 'idaho_county_clue_013', 13, NULL, NULL),
('idaho_counties', 'idaho_county_clue_014', 14, NULL, NULL),
('idaho_counties', 'idaho_county_clue_015', 15, NULL, NULL),
('idaho_counties', 'idaho_county_clue_016', 16, NULL, NULL),
('idaho_counties', 'idaho_county_clue_017', 17, NULL, NULL),
('idaho_counties', 'idaho_county_clue_018', 18, NULL, NULL),
('idaho_counties', 'idaho_county_clue_019', 19, NULL, NULL),
('idaho_counties', 'idaho_county_clue_020', 20, NULL, NULL),
('idaho_counties', 'idaho_county_clue_021', 21, NULL, NULL),
('idaho_counties', 'idaho_county_clue_022', 22, NULL, NULL),
('idaho_counties', 'idaho_county_clue_023', 23, NULL, NULL),
('idaho_counties', 'idaho_county_clue_024', 24, NULL, NULL),
('idaho_counties', 'idaho_county_clue_025', 25, NULL, NULL),
('idaho_counties', 'idaho_county_clue_026', 26, NULL, NULL),
('idaho_counties', 'idaho_county_clue_027', 27, NULL, NULL),
('idaho_counties', 'idaho_county_clue_028', 28, NULL, NULL),
('idaho_counties', 'idaho_county_clue_029', 29, NULL, NULL),
('idaho_counties', 'idaho_county_clue_030', 30, NULL, NULL),
('idaho_counties', 'idaho_county_clue_031', 31, NULL, NULL),
('idaho_counties', 'idaho_county_clue_032', 32, NULL, NULL),
('idaho_counties', 'idaho_county_clue_033', 33, NULL, NULL),
('idaho_counties', 'idaho_county_clue_034', 34, NULL, NULL),
('idaho_counties', 'idaho_county_clue_035', 35, NULL, NULL),
('idaho_counties', 'idaho_county_clue_036', 36, NULL, NULL),
('idaho_counties', 'idaho_county_clue_037', 37, NULL, NULL),
('idaho_counties', 'idaho_county_clue_038', 38, NULL, NULL),
('idaho_counties', 'idaho_county_clue_039', 39, NULL, NULL),
('idaho_counties', 'idaho_county_clue_040', 40, NULL, NULL),
('idaho_counties', 'idaho_county_clue_041', 41, NULL, NULL),
('idaho_counties', 'idaho_county_clue_042', 42, NULL, NULL),
('idaho_counties', 'idaho_county_clue_043', 43, NULL, NULL),
('idaho_counties', 'idaho_county_clue_044', 44, NULL, NULL),
('idaho_counties', 'idaho_code_clue_001', 45, NULL, NULL),
('idaho_counties', 'idaho_code_clue_002', 46, NULL, NULL),
('idaho_counties', 'idaho_code_clue_003', 47, NULL, NULL),
('idaho_counties', 'idaho_code_clue_004', 48, NULL, NULL),
('idaho_counties', 'idaho_code_clue_005', 49, NULL, NULL),
('idaho_counties', 'idaho_code_clue_006', 50, NULL, NULL),
('idaho_counties', 'idaho_code_clue_007', 51, NULL, NULL),
('idaho_counties', 'idaho_code_clue_008', 52, NULL, NULL),
('idaho_counties', 'idaho_code_clue_009', 53, NULL, NULL),
('idaho_counties', 'idaho_code_clue_010', 54, NULL, NULL),
('idaho_counties', 'idaho_code_clue_011', 55, NULL, NULL),
('idaho_counties', 'idaho_code_clue_012', 56, NULL, NULL),
('idaho_counties', 'idaho_code_clue_013', 57, NULL, NULL),
('idaho_counties', 'idaho_code_clue_014', 58, NULL, NULL),
('idaho_counties', 'idaho_code_clue_015', 59, NULL, NULL),
('idaho_counties', 'idaho_code_clue_016', 60, NULL, NULL),
('idaho_counties', 'idaho_code_clue_017', 61, NULL, NULL),
('idaho_counties', 'idaho_code_clue_018', 62, NULL, NULL),
('idaho_counties', 'idaho_code_clue_019', 63, NULL, NULL),
('idaho_counties', 'idaho_code_clue_020', 64, NULL, NULL),
('idaho_counties', 'idaho_code_clue_021', 65, NULL, NULL),
('idaho_counties', 'idaho_code_clue_022', 66, NULL, NULL),
('idaho_counties', 'idaho_code_clue_023', 67, NULL, NULL),
('idaho_counties', 'idaho_code_clue_024', 68, NULL, NULL),
('idaho_counties', 'idaho_code_clue_025', 69, NULL, NULL),
('idaho_counties', 'idaho_code_clue_026', 70, NULL, NULL),
('idaho_counties', 'idaho_code_clue_027', 71, NULL, NULL),
('idaho_counties', 'idaho_code_clue_028', 72, NULL, NULL),
('idaho_counties', 'idaho_code_clue_029', 73, NULL, NULL),
('idaho_counties', 'idaho_code_clue_030', 74, NULL, NULL),
('idaho_counties', 'idaho_code_clue_031', 75, NULL, NULL),
('idaho_counties', 'idaho_code_clue_032', 76, NULL, NULL),
('idaho_counties', 'idaho_code_clue_033', 77, NULL, NULL),
('idaho_counties', 'idaho_code_clue_034', 78, NULL, NULL),
('idaho_counties', 'idaho_code_clue_035', 79, NULL, NULL),
('idaho_counties', 'idaho_code_clue_036', 80, NULL, NULL),
('idaho_counties', 'idaho_code_clue_037', 81, NULL, NULL),
('idaho_counties', 'idaho_code_clue_038', 82, NULL, NULL),
('idaho_counties', 'idaho_code_clue_039', 83, NULL, NULL),
('idaho_counties', 'idaho_code_clue_040', 84, NULL, NULL),
('idaho_counties', 'idaho_code_clue_041', 85, NULL, NULL),
('idaho_counties', 'idaho_code_clue_042', 86, NULL, NULL),
('idaho_counties', 'idaho_code_clue_043', 87, NULL, NULL),
('idaho_counties', 'idaho_code_clue_044', 88, NULL, NULL)
ON CONFLICT (collection_id, clue_id) DO UPDATE SET
  "order" = EXCLUDED."order";

UPDATE clue_collection
SET clue_count = 88,
    modified_date = now()
WHERE id = 'idaho_counties';
